self_signed_certs:
  - ca_cert_name: ibm-bm3-nodepool.crt
    ca_cert: |
      -----BEGIN CERTIFICATE-----
      MIIFKjCCAxKgAwIBAgIUVKfpwKl1xB4sQOl/C5HjbZmn20YwDQYJKoZIhvcNAQEL
      BQAwEzERMA8GA1UEAwwIc2ltcGxlY2EwHhcNMjMxMTIwMTUyMTM2WhcNMzMxMTE3
      MTUyMTM2WjAVMRMwEQYDVQQDDApzdGFuZGFsb25lMIICIjANBgkqhkiG9w0BAQEF
      AAOCAg8AMIICCgKCAgEApRlM899s1rA37Mu4NLPlGCMW5Tl9VPpIf2wjcwH/14q5
      QNw6Id0j0XREr1DYj66fnnONaog4t8xmqHkHVny9XoqPzsy9pscph5jEMWkRT6sj
      I1liY0719GrinR/fPM7neK/jodzOxvqlX+QWmLvJhj7x7HkNvYdJ7K1hvUmL8lGc
      BLiqUl5HWuinzCUeDsmD+oC3mA8M7KpGdnEghlb4BwY72OMwVlV6B5Aym7Vug2Q4
      7Tg14uYHx1xIBdH7hFuwnQXVci4AbjViCi7u6v5LxbqSKvk2K0aIEuwNKru5jL8Q
      WkK5bNBD2ZCgOuda4V/7t+kKsIDW2+9qURphJgJBbPVqzsnF8f54Vm2TldfdBhui
      LWInwuwA43qyzRH0yiLZ61BOFoutXG8sfEu4G9JK2cxykUhjP9Khga3kYCW5alBA
      x4uja3FTs9FU847upaTowKDClWHFAJL3wvbrRMrSGW8/fiMUTZHFf7r6INPrQM3b
      2WPewP6b2lFeqho3dVeh3IlTNVht5QclLxrKiTet3To14qdB8sreb3l1wqNUFaxJ
      hxbCb00zTWkzFdFWlUg87ZUSdQiCQf8GszjpjPb9dwXeh3sLzuZr67ltRtnYcfXV
      ijQBhhvhy1Fnq8ea+jd5PCWYUpjg6EBCPwm+n4V1enI0XQmMKSNSW2BF+3UdsIkC
      AwEAAaN0MHIwMAYDVR0RBCkwJ4IKc3RhbmRhbG9uZYINMTY5LjYwLjQ5LjIyNocE
      qTwx4ocEwKgYAjAdBgNVHQ4EFgQUV6T4enghwVLYq4uc1GMiG9DTgSEwHwYDVR0j
      BBgwFoAUkG5/A8Te06p70dxYwYTX4GoR0N0wDQYJKoZIhvcNAQELBQADggIBAJum
      dHJ2s4NtayV+TDeGsZdMKoK759X+X/32e1e7A/6SrXnbIVs300v5t5Pe1X93ZoRL
      cYc2//1PtMuYxOHAz+tOFurbNd/pKxS1RxUjHPMgzV1yMnKkZS/kfu0xFLd8TyLr
      4cSzmymB9c9JW68gWL8zAGoEDUdxW6r6UJVJoIpTutA0V0OjAs9pBW2Wqsle5/DH
      1hJs8Bgda7Y0h5yB2zPYTSs3PyzboTmWagynst6C/swJ2xPkx6VYJIwU3FUaCFry
      Aui88nyBGS/yazd/mmPLhXJly0l2A7RQeV+XVMnu1DB/gpVayn9jA4rZ8alrksup
      2AIw70cPv+uSnSYj0s+K66pDKc0CayUmeuGi0Q3xh2etgpNyuX/FRiVdlo9uuXnl
      5M9VTFuWt6KWksYZ+LJ6xXU+pcQohnt0xYROU0PEZiZRh9MH5i7f6KHwIM3W/64/
      vo4cg2hf6TVFzNyMbzrl/Ddp/aZton4G4UzlCMaIhWI5RMRRSmyoitPRRYn2iIZF
      MBfLPILrFvp8U1hkgde0u2p4wmRJG9Q8hqiS0tQvwI8eSgYIXWIiVvnyrxb4LBj3
      kJW1Na/512Nwqhho2o2ZAuULoP4nPWtV76YK3tmeVAy+vzyUEhREVN9eMkaBqaSH
      M4o6e+d6UKeNdvZOSjbfsuuLPqSdUFuVqNuHMt75
      -----END CERTIFICATE-----
  - ca_cert_name: ibm-bm4-nodepool.crt
    ca_cert: |
      -----BEGIN CERTIFICATE-----
      MIIFKjCCAxKgAwIBAgIUFx5LsVuK7UJ/CjLPlpB2Mu1ryIwwDQYJKoZIhvcNAQEL
      BQAwEzERMA8GA1UEAwwIc2ltcGxlY2EwHhcNMjMxMTIwMTgzMTQwWhcNMzMxMTE3
      MTgzMTQwWjAVMRMwEQYDVQQDDApzdGFuZGFsb25lMIICIjANBgkqhkiG9w0BAQEF
      AAOCAg8AMIICCgKCAgEAqaMvY6hAGo/RSrPFxuM3ApJ0PVlh0WCiI5YcLm1xE/Hc
      m3GoOD8+QSdWoxgwviI6GyS+th4uhs6ttZ2BvNllosLaM8EVzofXvr+brdIc1AV6
      BJn2t8DbL7WZX6f3RZmRfkHkEKzhATEUpF9S74xXI4JF2uEXCj0+u4UriHzwF/8v
      25DbOLi9QtVGvzd+6W32ZvZOuD+HhP21yaoimP2SAyAw6amKFAKGOYI153bZtE78
      k+uCMNNcR/B1HdsyM1ct9q9rnJCFdeBqsQ8nUa6ep3LmZi1bk4q8e9VkaPtWGqr9
      eOoyA8v6DPLrP16Xh8+ItyGStAFkDHCVmPtMM3SF3LSg/n5qm0VOom1t2GHfUehR
      vlEsMVGwZWasaNJ2eWYKPx4PP4Y4vqH1uzn2alvcANg4ZvdgkvEQiu8aYZObii0H
      /Pw9+/Ma1QUg3+JNzZSUb4P5QwLcJ4OSW8LFQaPk5t3c8OtPB6Gs8e+yVfh4wL90
      +Df/Vbm0ggK+F5cDky+b4kGv1cdvt5UybvBFReeBBeAGHaWNfu/PAeS+N6sNaRLx
      vlBE/oiDzPmsBt+YXnFp0UkhP3VWi8Sbj+FmNI9IFSn9RBZ9Hn26GRA/phWxRleO
      8Akp+3XiI6iTaK5SSAT16vxFj8qITHfY9s3DzyRr0wTOp2NDM59b6os5IvrZaP8C
      AwEAAaN0MHIwMAYDVR0RBCkwJ4IKc3RhbmRhbG9uZYINMTY5LjYwLjQ5LjIzM4cE
      qTwx6YcEwKgYAjAdBgNVHQ4EFgQUjTD4/BhI/rPX8hjpQdGMBaUJT78wHwYDVR0j
      BBgwFoAUKomD0H5NF57Yt3U+TuN6sCpaL7UwDQYJKoZIhvcNAQELBQADggIBAKQy
      NjJ9VNou5y7rr139UevyFEZTnW9eTWldnnBYgjREEo9+eUwaH06XEGBD4rmhIXyb
      kzsxVq8ybrlAny4+7B0HAdAgIxNM6Dw5r4AR2l2fZmpenBJWoUKSMYIv91oLtkZD
      NpJ96s1N7ghYamGQ2evYmiF+lOgaJBchttknKYhG/hTREpWg4+t4XuXrSlJZ2joh
      PPsY9dnDnOwgP8pKsN8Kd2j48WSZ8I3JXFSzEH9SlqJroDm3h3ATipIcS7DNGRUf
      q6RXVtbx0LGKBjIrrBiRLETbv/pgUP2F3En6H8Qdsflk61mbuQ/+m8y577mKeaDD
      GkeCjWakcR1PCyyUY+ZY4XBma7CHB5nT/QXIMRIAjDMQkBU/vZQfa9yfteYZiYBD
      oWwMqNdLqwuDtH+HwQU7XtN6Xj6roifws8qBai0Sgjuw5GVtAuBe4rcRidvuA5av
      uqRDfgUTD1erUM7ZyyqkNnLjavG0KcHky7w0Ca7BblPatfqMR4L0b+snA3OCZuC5
      dm+PMRLb7BOXpBWV/HnKjOvf060T0WQtRg/oCpVn0+e74b/CZ/cpWPYm8/fdDqN+
      T/bouUs39nrQxbcjXnImMcWwVscYjr6WYHQGJv+P8WTfmB1evn9F9P8kDELy1NRV
      nYcsyHyTzPrgyeGo2VtxSGzEW1dttqMJYaHKcZDV
      -----END CERTIFICATE-----
