sf_ssh_priv_key: "{{ install_server_sf_key }}"
acme_vhost_owner: "pagesuser"
acme_domains:
  - domain: docs.softwarefactory-project.io
    vhost_root: /var/www/pages/docs.softwarefactory-project.io/
  - domain: www.softwarefactory-project.io
    vhost_root: /var/www/pages/www.softwarefactory-project.io/
  - domain: softwarefactory-project.io
    sf_gateway: true
    vhost_skip: true

monitoring_host_url: https://monitoring.softwarefactory-project.io
weeder_host: image-builder.softwarefactory-project.io
logjuicer_host: gateway-cloud-softwarefactory.apps.ocp.cloud.ci.centos.org

# Anubis config
anubis_domain: softwarefactory-project.io
anubis_target_port: 8083
anubis_allowed_ip_ranges:
  # Vexxhost IP ranges
  - 38.102.83.0/24
  - 38.129.56.0/24
  - 2604:e100:4::/64
  # TODO? Individual IPs of centosinfra-prod
  # TODO? IP range of red hat public IPs (for queries coming from downstream sf)
