---
- name: Set hostname
  become: true
  hostname:
    name: "{{ fqdn }}"

- name: Install required system packages
  become: true
  yum:
    name:
      - iproute-tc
      - git
      - golang
      - rpm-ostree
    state: present

- name: Add host to the hosts file
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ fqdn }}$"
    line: "{{ ansible_default_ipv4.address }} {{ fqdn }}"
    state: present

# From Kubernetes setup - https://kubernetes.io/docs/setup/production-environment/container-runtimes/
- name: Add modules to be loaded
  become: true
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf

- name: Enable module
  become: true
  shell: |
    modprobe br_netfilter
    modprobe overlay

- name: Update sysctl
  become: true
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.ipv6.conf.all.disable_ipv6      = 1
      net.ipv6.conf.default.disable_ipv6  = 1
    dest: /etc/sysctl.d/10-k8s.conf
  register: _k8s_sysctl

- name: Restart sysctl service
  become: true
  service:
    name: systemd-sysctl
    state: restarted
  when: _k8s_sysctl.changed
