---
- name: Install epel-release to get kubernetes-client
  become: true
  ansible.builtin.package:
    name: epel-release
    state: latest

- name: Install required packages
  become: true
  ansible.builtin.package:
    name:
      - python3
      - podman
      - curl
    state: present

# https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
- name: Get last kubectl release
  ansible.builtin.shell: |
    curl -L -s https://dl.k8s.io/release/stable.txt
  register: _last_kubernetes_stable

- name: Download kubernetes client binary
  become: true
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ _last_kubernetes_stable.stdout }}/bin/linux/amd64/kubectl"
    dest: /usr/bin/kubectl
    mode: '0755'

# NOTE: Increase limits for nproc and nofile due error:
# pthread_create failed (eagain)
# NOTE(dpawlik): Default value for nofile is 1024.
- name: Set limits for nofile
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/security/limits.conf
    line: '* - nofile 102400'
    insertbefore: '^# End of file'
    state: present

 # NOTE(dpawlik): Default value for nproc is: 63844
- name: Set limits for nproc
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/security/limits.conf
    line: '* - nproc unlimited'
    insertbefore: '^# End of file'
    state: present

# Increase value for inodes to avoid error:
# "failed to create fsnotify watcher: too many open files"
# Current values for: max_user_watches: 524288,  max_user_instances=128
- name: Set inode limits
  become: true
  ansible.builtin.shell: |
    sysctl -w fs.inotify.max_user_watches=5242880
    sysctl -w fs.inotify.max_user_instances=1280

### OPTIONAL ###
# NOTE: This configuration is needed by Opensearch service
# https://opensearch.org/docs/opensearch/install/important-settings/
- name: Set important settings for Opensearch container
  become: true
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: true
