---
fqdn: microshift.dev
openshift_pull_secret: ""
registry_secret_path: /etc/crio/openshift-pull-secret
disable_selinux: false
hide_sensitive_logs: false
setup_tools: true

use_copr_microshift: false
microshift_version: 4.12

# curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
kubernetes_version: "v1.24.1"
kompose_version: "v1.26.1"
kustomize_version: "v4.5.5"
opm_version: "4.6.1"
helm_version: "v3.9.0"
local_storage_version: "v0.0.22"

setup_olm: false
repo_dir: "~{{ ansible_user }}/repos"
operator_sdk_version: "v1.21.0"
operator_sdk_url: "https://github.com/operator-framework/operator-sdk"

create_pv: true
pv_storageclass: manual
pv_host_path: "/mnt/data"
pv_count: start=1 end=10

delete_openshift_storage: true
